### ISSUE TITLE
Random freezes

### ISSUE THREAD

**Issue by ecribia** [rdavison/typocide#8]
Hey! Ive been running this on NixOS for quite a while without any issues, however i recently have had problems with random freezes. On average the program freezes after about 7 words. It always happens after i finish writing the word and press space. Any new updates that caused this?

**Comment by rdavison** [comment]
This has been happening to me too. Can you try the previous commit?

**Comment by ecribia** [comment]
Just tried it out, and the previous commit seems to work fine :) will use that one for now at least. Thanks for the quick reply!

**Comment by rdavison** [comment]
No problem. I think I'm going to revert that commit. It's just broken.

**Comment by rdavison** [comment]
Done in https://github.com/rdavison/typocide/commit/8d2b7a79b881b3b0a049e29e58231d3537786c4d
